# =============================================================================
# PANDAS EXCERCISES
# =============================================================================


# 

# 

# importing the panadas


In [64]:
import numpy as np
import pandas as pd

# creating a dataframe fruits


In [65]:
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})

fruits

Apples  Bananas
0      30       21

 # creating a dataframe fruit_sales


In [66]:
fruit_sales = pd.DataFrame({"Apples": [35, 41], "Bananas": [
                           21, 34]}, index=(["2017 Sales", "2018 Sales"]))

fruit_sales

Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# creating a series ingredients


In [67]:
ingredients = pd.Series(
    {"Flour": "4 Cups", "Milk": "1 Cup", "Eggs": "2 large", "Spam": "1 Can"})

ingredients

Flour     4 Cups
Milk       1 Cup
Eggs     2 large
Spam       1 Can
dtype: object

#  reading the csv dataset of wine reviews into  a Dataframe reviews


In [68]:
reviews = pd.read_csv("~/KUBUNTU/DATASET/CSV_FILES/winemag-data_first150k.csv")

reviews.head()

Unnamed: 0 country                                        description  \
0           0      US  This tremendous 100% varietal wine hails from ...   
1           1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2           2      US  Mac Watson honors the memory of a wine once ma...   
3           3      US  This spent 20 months in 30% new French oak, an...   
4           4  France  This is the top wine from La Bégude, named aft...   

                            designation  points  price        province  \
0                     Martha's Vineyard      96  235.0      California   
1  Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2         Special Selected Late Harvest      96   90.0      California   
3                               Reserve      96   65.0          Oregon   
4                            La Brûlade      95   66.0        Provence   

            region_1           region_2             variety  \
0        Napa Valley               Napa  Cabernet Sauvignon   
1               Toro                NaN       Tinta de Toro   
2     Knights Valley             Sonoma     Sauvignon Blanc   
3  Willamette Valley  Willamette Valley          Pinot Noir   
4             Bandol                NaN  Provence red blend   

                    winery  
0                    Heitz  
1  Bodega Carmen Rodríguez  
2                 Macauley  
3                    Ponzi  
4     Domaine de la Bégude

#  describe the dataset


In [69]:
desc = reviews.describe()

desc

Unnamed: 0         points          price
count  150930.000000  150930.000000  137235.000000
mean    75464.500000      87.888418      33.131482
std     43569.882402       3.222392      36.322536
min         0.000000      80.000000       4.000000
25%     37732.250000      86.000000      16.000000
50%     75464.500000      88.000000      24.000000
75%    113196.750000      90.000000      40.000000
max    150929.000000     100.000000    2300.000000

#  create and display a DataFrame called `animals`


In [70]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=[
                       'Year 1', 'Year 2'])

animals

Cows  Goats
Year 1    12     22
Year 2    20     19

# code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`


In [71]:
animals.to_csv("~/KUBUNTU/DATASET/CSV_FILES/cows_and_goats.csv")

# select the description column from reviews and assign it to variable desc


In [72]:
desc = reviews["description"]

desc

0         This tremendous 100% varietal wine hails from ...
1         Ripe aromas of fig, blackberry and cassis are ...
2         Mac Watson honors the memory of a wine once ma...
3         This spent 20 months in 30% new French oak, an...
4         This is the top wine from La Bégude, named aft...
                                ...                        
150925    Many people feel Fiano represents southern Ita...
150926    Offers an intriguing nose with ginger, lime an...
150927    This classic example comes from a cru vineyard...
150928    A perfect salmon shade, with scents of peaches...
150929    More Pinot Grigios should taste like this. A r...
Name: description, Length: 150930, dtype: object

# check the type of the variable desc is


In [73]:
print(type(desc))

<class 'pandas.core.series.Series'>


# select first column from description column of reviews and assign it to ariable first_description


In [74]:
first_description = reviews["description"][0]

first_description

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

# select first row of the data from reviews and assign it to first_row


In [75]:
first_row = reviews.iloc[0]

first_row

Unnamed: 0                                                     0
country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                      235.0
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

# select the first 10 values from the description column in reviews and assign to variable first_descriptions


In [76]:
first_descriptions = reviews["description"][:10]

first_descriptions

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
3    This spent 20 months in 30% new French oak, an...
4    This is the top wine from La Bégude, named aft...
5    Deep, dense and pure from the opening bell, th...
6    Slightly gritty black-fruit aromas include a s...
7    Lush cedary black-fruit aromas are luxe and of...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, dtype: object

# select the records with index labels 1,2,3,5,8 and assign to varible sample_reviews


In [77]:
sample_reviews = reviews.iloc[[1, 2, 3, 5, 8], :]


sample_reviews

Unnamed: 0 country                                        description  \
1           1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2           2      US  Mac Watson honors the memory of a wine once ma...   
3           3      US  This spent 20 months in 30% new French oak, an...   
5           5   Spain  Deep, dense and pure from the opening bell, th...   
8           8      US  This re-named vineyard was formerly bottled as...   

                            designation  points  price        province  \
1  Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2         Special Selected Late Harvest      96   90.0      California   
3                               Reserve      96   65.0          Oregon   
5                             Numanthia      95   73.0  Northern Spain   
8                                Silice      95   65.0          Oregon   

             region_1           region_2          variety  \
1                Toro                NaN    Tinta de Toro   
2      Knights Valley             Sonoma  Sauvignon Blanc   
3   Willamette Valley  Willamette Valley       Pinot Noir   
5                Toro                NaN    Tinta de Toro   
8  Chehalem Mountains  Willamette Valley       Pinot Noir   

                    winery  
1  Bodega Carmen Rodríguez  
2                 Macauley  
3                    Ponzi  
5                Numanthia  
8                Bergström

# create a variable df have country, province, region_1, region_2, columns with index labels 0,1,10,100


In [78]:
df = reviews[["description", "country", "province",
              "region_1", "region_2"]].iloc[[0, 1, 10, 100]]

df

description country  \
0    This tremendous 100% varietal wine hails from ...      US   
1    Ripe aromas of fig, blackberry and cassis are ...   Spain   
10   Elegance, complexity and structure come togeth...   Italy   
100  Juicy kiwi, lime blossom and sour apple candy ...      US   

               province     region_1     region_2  
0            California  Napa Valley         Napa  
1        Northern Spain         Toro          NaN  
10   Northeastern Italy       Collio          NaN  
100          California  South Coast  South Coast

# a variable df containing country and variety column first 100 records


In [79]:
df = reviews[["country", "variety"]].iloc[:100, ]

df

country               variety
0       US    Cabernet Sauvignon
1    Spain         Tinta de Toro
2       US       Sauvignon Blanc
3       US            Pinot Noir
4   France    Provence red blend
..     ...                   ...
95  France         Malbec-Merlot
96      US            Chardonnay
97      US    Cabernet Sauvignon
98  France         Merlot-Malbec
99  France  Ugni Blanc-Colombard

[100 rows x 2 columns]

#  craete a datframe italian_wines having reviews of wines made in Italy


In [80]:
italian_wines = reviews.loc[reviews["country"] == "Italy"]


italian_wines

Unnamed: 0 country                                        description  \
10              10   Italy  Elegance, complexity and structure come togeth...   
32              32   Italy  Underbrush, scorched earth, menthol and plum s...   
35              35   Italy  Forest floor, tilled soil, mature berry and a ...   
37              37   Italy  Aromas of forest floor, violet, red berry and ...   
38              38   Italy  This has a charming nose that boasts rose, vio...   
...            ...     ...                                                ...   
150920      150920   Italy  Rich and mature aromas of smoke, earth and her...   
150922      150922   Italy  Made by 30-ish Roberta Borghese high above Man...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

               designation  points  price            province  \
10      Ronco della Chiesa      95   80.0  Northeastern Italy   
32           Vigna Piaggia      90    NaN             Tuscany   
35                 Riserva      90  135.0             Tuscany   
37                     NaN      90   29.0             Tuscany   
38                     NaN      90   23.0             Tuscany   
...                    ...     ...    ...                 ...   
150920        Brut Riserva      91   19.0  Northeastern Italy   
150922           Superiore      91    NaN  Northeastern Italy   
150925                 NaN      91   20.0      Southern Italy   
150927       Terre di Dora      91   20.0      Southern Italy   
150929                 NaN      90   15.0  Northeastern Italy   

                            region_1 region_2          variety  \
10                            Collio      NaN         Friulano   
32            Brunello di Montalcino      NaN       Sangiovese   
35            Brunello di Montalcino      NaN       Sangiovese   
37      Vino Nobile di Montepulciano      NaN       Sangiovese   
38                  Chianti Classico      NaN       Sangiovese   
...                              ...      ...              ...   
150920                        Trento      NaN  Champagne Blend   
150922    Colli Orientali del Friuli      NaN            Tocai   
150925             Fiano di Avellino      NaN      White Blend   
150927             Fiano di Avellino      NaN      White Blend   
150929                    Alto Adige      NaN     Pinot Grigio   

                       winery  
10           Borgo del Tiglio  
32            Abbadia Ardenga  
35                   Carillon  
37                 Avignonesi  
38           Casina di Cornia  
...                       ...  
150920                Letrari  
150922      Ronchi di Manzano  
150925  Feudi di San Gregorio  
150927              Terredora  
150929          Alois Lageder  

[23478 rows x 11 columns]

# create a datafrme top_oceania_wines with all reviews having atleast 95 points out of 100 for wines from Australia and New Zealand


In [81]:
top_oceania_wines = reviews.loc[(reviews["country"].isin(
    ["Australia", "New Zealand"])) & (reviews["points"] >= 95)]


top_oceania_wines

Unnamed: 0    country  \
2148          2148  Australia   
2458          2458  Australia   
3033          3033  Australia   
3044          3044  Australia   
3047          3047  Australia   
...            ...        ...   
122779      122779  Australia   
127614      127614  Australia   
137383      137383  Australia   
150562      150562  Australia   
150563      150563  Australia   

                                              description  \
2148    Full-bodied and plush yet vibrant and imbued w...   
2458    This is a top example of the classic Australia...   
3033    This Cabernet equivalent to Grange has explode...   
3044    From vines planted in 1912, this has been an i...   
3047    This is a throwback to those brash, flavor-exu...   
...                                                   ...   
122779  If Standish's Relic is the feminine side of Sh...   
127614  This stellar wine takes a little time in the g...   
137383  The 2007 Astralis impresses for its combinatio...   
150562  As unevolved as they are, the dense and multil...   
150563  Seamless luxury from stem to stern, this ‘baby...   

                         designation  points  price         province  \
2148                      The Factor      98  125.0  South Australia   
2458                       The Peake      96  150.0  South Australia   
3033                         Bin 707      95  500.0  South Australia   
3044        Mount Edelstone Vineyard      95  200.0  South Australia   
3047                             One      95   95.0  South Australia   
...                              ...     ...    ...              ...   
122779  The Standish Single Vineyard      96  135.0  South Australia   
127614                 Hill of Grace      95  625.0  South Australia   
137383                      Astralis      95  225.0  South Australia   
150562                        Grange      96  185.0  South Australia   
150563                           RWT      95   70.0  South Australia   

               region_1 region_2             variety           winery  
2148     Barossa Valley      NaN              Shiraz         Torbreck  
2458       McLaren Vale      NaN     Cabernet-Shiraz     Hickinbotham  
3033    South Australia      NaN  Cabernet Sauvignon         Penfolds  
3044        Eden Valley      NaN              Shiraz         Henschke  
3047    Langhorne Creek      NaN           Red Blend        Heartland  
...                 ...      ...                 ...              ...  
122779   Barossa Valley      NaN              Shiraz         Standish  
127614      Eden Valley      NaN              Shiraz         Henschke  
137383        Clarendon      NaN               Syrah  Clarendon Hills  
150562  South Australia      NaN              Shiraz         Penfolds  
150563   Barossa Valley      NaN              Shiraz         Penfolds  

[82 rows x 11 columns]

# find tjhe median of the points column


In [82]:
median_points = reviews["points"].median()


median_points

88.0

# what countries in dataset


In [83]:
countries_unique = reviews["country"].unique()


countries_unique

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

# create reviews_per_country variable mapping countries to the count of reviews of wines from that country


In [84]:
reviews_per_country = reviews["country"].value_counts()


reviews_per_country

US                        62397
Italy                     23478
France                    21098
Spain                      8268
Chile                      5816
Argentina                  5631
Portugal                   5322
Australia                  4957
New Zealand                3320
Austria                    3057
Germany                    2452
South Africa               2258
Greece                      884
Israel                      630
Hungary                     231
Canada                      196
Romania                     139
Slovenia                     94
Uruguay                      92
Croatia                      89
Bulgaria                     77
Moldova                      71
Mexico                       63
Turkey                       52
Georgia                      43
Lebanon                      37
Cyprus                       31
Brazil                       25
Macedonia                    16
Serbia                       14
Morocco                      12
England 

# craete centered_price having version of price column with mean malue subtarcted


In [85]:
centered_price = reviews["price"]-reviews["price"].mean()


centered_price

0         201.868518
1          76.868518
2          56.868518
3          31.868518
4          32.868518
             ...    
150925    -13.131482
150926     -6.131482
150927    -13.131482
150928     18.868518
150929    -18.131482
Name: price, Length: 150930, dtype: float64

#  create variable bargain_wine with the title of the wine with the highest points-to-price ratio


In [86]:
bargain_idx = (reviews["points"]/reviews["price"]).idxmax()

bargain_wine = reviews.loc[bargain_idx]["winery"]

bargain_wine

'Bandit'

# create a series descriptor_counts to count how many the words "tropical" or "fruity" appear


In [87]:
trop = reviews["description"].map(lambda desc: "tropical" in desc).sum()


fruit = reviews["description"].map(lambda desc: "fruity" in desc).sum()


descriptor_counts = pd.Series([trop, fruit], index=["tropical", "fruity"])


descriptor_counts

tropical    4135
fruity      8669
dtype: int64

# create variable star_ratings with number of strs regarding the each review in dataset


In [88]:
def rating(row):

    if row.country == "Canada":

        return 3
    elif row.points >= 95:

        return 3
    elif row.points >= 85:

        return 2

    else:

        return 1


star_ratings = reviews.apply(rating, axis="columns")

star_ratings

0         3
1         3
2         3
3         3
4         3
         ..
150925    2
150926    2
150927    2
150928    2
150929    2
Length: 150930, dtype: int64

# create series whose index is variety and whose value counts how many review each person wrote


In [89]:
reviews_written = reviews.groupby('variety').variety.count()

reviews_written

variety
Agiorgitiko                120
Aglianico                  317
Aidani                       1
Airen                        6
Albana                      17
                          ... 
Zierfandler-Rotgipfler       3
Zinfandel                 3799
Zlahtina                     4
Zweigelt                   219
Žilavka                      2
Name: variety, Length: 632, dtype: int64

# Create a Series whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending order


In [90]:
best_rating_per_price = reviews.groupby('price')['points'].max().sort_index()

best_rating_per_price

price
4.0        86
5.0        90
6.0        90
7.0        90
8.0        91
         ... 
1300.0     96
1400.0    100
1900.0     98
2013.0     91
2300.0     99
Name: points, Length: 357, dtype: int64

# Create a DataFrame whose index is the variety category from the dataset and whose values are the min and max values thereof.


In [91]:
price_extremes = reviews.groupby('variety').price.agg([min, max])


price_extremes

min    max
variety                            
Agiorgitiko              8.0   65.0
Aglianico                6.0  130.0
Aidani                  27.0   27.0
Airen                    8.0   10.0
Albana                   8.0   66.0
...                      ...    ...
Zierfandler-Rotgipfler  20.0   25.0
Zinfandel                4.0  100.0
Zlahtina                13.0   17.0
Zweigelt                 9.0   70.0
Žilavka                 13.0   15.0

[632 rows x 2 columns]

# Create a variable sorted_varieties containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).


In [92]:
sorted_varieties = price_extremes.sort_values(
    by=['min', 'max'], ascending=False)


sorted_varieties

min    max
variety                                     
Cabernet-Shiraz                 150.0  150.0
Mazuelo                          92.0  105.0
Carignan-Syrah                   80.0   80.0
Syrah-Cabernet Franc             69.0   69.0
Nasco                            65.0   65.0
...                               ...    ...
Rabigato                          NaN    NaN
Sacy                              NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Terret Blanc                      NaN    NaN
Zelen                             NaN    NaN

[632 rows x 2 columns]

# Create a Series whose index is reviewers and whose values is the average review score given out by that reviewer.


In [93]:
reviewer_mean_ratings = reviews.groupby('designation').points.mean()


reviewer_mean_ratings

designation
"M"                    84.0
#50 Mon Chou           88.0
#SocialSecret          86.0
'72                    87.0
'A Naca Rosso          88.0
                       ... 
étoile Brut            90.0
ía                     85.0
ía Crianza             85.0
Župska                 88.0
‘Rough Justice' Red    89.0
Name: points, Length: 30621, dtype: float64

# Create a Series whose index is a MultiIndexof {country, variety} pairs.


In [94]:
country_variety_counts = reviews.groupby(
    ['country', 'variety']).size().sort_values(ascending=False)


country_variety_counts

country      variety                 
US           Pinot Noir                  10340
             Cabernet Sauvignon           9178
             Chardonnay                   8127
France       Bordeaux-style Red Blend     4960
US           Syrah                        4274
                                         ...  
France       Pied de Perdrix                 1
Tunisia      White Blend                     1
             Rosé                            1
Switzerland  White Blend                     1
US           Carignan-Grenache               1
Length: 1475, dtype: int64

# What is the data type of the points column in the dataset


In [95]:
dtype = reviews.points.dtype


dtype

dtype('int64')

# Create a Series from entries in the `points` column, but convert the entries to strings.


In [96]:
point_strings = reviews.points.astype(str)


point_strings

0         96
1         96
2         96
3         96
4         95
          ..
150925    91
150926    91
150927    91
150928    90
150929    90
Name: points, Length: 150930, dtype: object

# How many reviews in the dataset are missing a price?


In [97]:
n_missing_prices = reviews.price.isnull().sum()


n_missing_prices

13695

# Create a Series counting the number of times each value occurs in the region_1 field. This field is often missing data, so replace missing values with Unknown. Sort in descending order.


In [98]:
reviews_per_region = reviews.region_1.fillna(
    'Unknown').value_counts().sort_values(ascending=False)


reviews_per_region

Unknown                                  25060
Napa Valley                               6209
Columbia Valley (WA)                      4975
Mendoza                                   3586
Russian River Valley                      3571
                                         ...  
Ramandolo                                    1
Côtes du Roussillon Villages Caramany        1
Vin de Pays de la Vallée de l’Aude           1
Rivesaltes Rosé                              1
Prince Edward County                         1
Name: region_1, Length: 1237, dtype: int64

# `region_1` and `region_2` are pretty uninformative names for locale columns in the dataset. Create a copy of `reviews` with these columns renamed to `region` and `locale`, respectively.


In [99]:
renamed = reviews.rename(columns=dict(region_1='region', region_2='locale'))


renamed

Unnamed: 0 country                                        description  \
0                0      US  This tremendous 100% varietal wine hails from ...   
1                1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2                2      US  Mac Watson honors the memory of a wine once ma...   
3                3      US  This spent 20 months in 30% new French oak, an...   
4                4  France  This is the top wine from La Bégude, named aft...   
...            ...     ...                                                ...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150926      150926  France  Offers an intriguing nose with ginger, lime an...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150928      150928  France  A perfect salmon shade, with scents of peaches...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

                                 designation  points  price  \
0                          Martha's Vineyard      96  235.0   
1       Carodorum Selección Especial Reserva      96  110.0   
2              Special Selected Late Harvest      96   90.0   
3                                    Reserve      96   65.0   
4                                 La Brûlade      95   66.0   
...                                      ...     ...    ...   
150925                                   NaN      91   20.0   
150926                        Cuvée Prestige      91   27.0   
150927                         Terre di Dora      91   20.0   
150928                       Grand Brut Rosé      90   52.0   
150929                                   NaN      90   15.0   

                  province             region             locale  \
0               California        Napa Valley               Napa   
1           Northern Spain               Toro                NaN   
2               California     Knights Valley             Sonoma   
3                   Oregon  Willamette Valley  Willamette Valley   
4                 Provence             Bandol                NaN   
...                    ...                ...                ...   
150925      Southern Italy  Fiano di Avellino                NaN   
150926           Champagne          Champagne                NaN   
150927      Southern Italy  Fiano di Avellino                NaN   
150928           Champagne          Champagne                NaN   
150929  Northeastern Italy         Alto Adige                NaN   

                   variety                   winery  
0       Cabernet Sauvignon                    Heitz  
1            Tinta de Toro  Bodega Carmen Rodríguez  
2          Sauvignon Blanc                 Macauley  
3               Pinot Noir                    Ponzi  
4       Provence red blend     Domaine de la Bégude  
...                    ...                      ...  
150925         White Blend    Feudi di San Gregorio  
150926     Champagne Blend                H.Germain  
150927         White Blend                Terredora  
150928     Champagne Blend                   Gosset  
150929        Pinot Grigio            Alois Lageder  

[150930 rows x 11 columns]

# Set the index name in the dataset to `wines`.


In [100]:
reindexed = reviews.rename_axis('wines', axis='rows')


reindexed

Unnamed: 0 country                                        description  \
wines                                                                           
0                0      US  This tremendous 100% varietal wine hails from ...   
1                1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2                2      US  Mac Watson honors the memory of a wine once ma...   
3                3      US  This spent 20 months in 30% new French oak, an...   
4                4  France  This is the top wine from La Bégude, named aft...   
...            ...     ...                                                ...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150926      150926  France  Offers an intriguing nose with ginger, lime an...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150928      150928  France  A perfect salmon shade, with scents of peaches...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

                                 designation  points  price  \
wines                                                         
0                          Martha's Vineyard      96  235.0   
1       Carodorum Selección Especial Reserva      96  110.0   
2              Special Selected Late Harvest      96   90.0   
3                                    Reserve      96   65.0   
4                                 La Brûlade      95   66.0   
...                                      ...     ...    ...   
150925                                   NaN      91   20.0   
150926                        Cuvée Prestige      91   27.0   
150927                         Terre di Dora      91   20.0   
150928                       Grand Brut Rosé      90   52.0   
150929                                   NaN      90   15.0   

                  province           region_1           region_2  \
wines                                                              
0               California        Napa Valley               Napa   
1           Northern Spain               Toro                NaN   
2               California     Knights Valley             Sonoma   
3                   Oregon  Willamette Valley  Willamette Valley   
4                 Provence             Bandol                NaN   
...                    ...                ...                ...   
150925      Southern Italy  Fiano di Avellino                NaN   
150926           Champagne          Champagne                NaN   
150927      Southern Italy  Fiano di Avellino                NaN   
150928           Champagne          Champagne                NaN   
150929  Northeastern Italy         Alto Adige                NaN   

                   variety                   winery  
wines                                                
0       Cabernet Sauvignon                    Heitz  
1            Tinta de Toro  Bodega Carmen Rodríguez  
2          Sauvignon Blanc                 Macauley  
3               Pinot Noir                    Ponzi  
4       Provence red blend     Domaine de la Bégude  
...                    ...                      ...  
150925         White Blend    Feudi di San Gregorio  
150926     Champagne Blend                H.Germain  
150927         White Blend                Terredora  
150928     Champagne Blend                   Gosset  
150929        Pinot Grigio            Alois Lageder  

[150930 rows x 11 columns]

# =============================================================================
# NUMPY EXCERCISES
# =============================================================================



# NumPy Creating Array


##  importing the numpy library

# Create a NumPy ndarray Object


In [101]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Use a tuple to create a NumPy array:


In [102]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


# Create a 0-D array with value 42


In [103]:
arr = np.array(42)

print(arr)

42


# Create a 1-D array containing the values 1,2,3,4,5:


In [104]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:


In [105]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:


In [106]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check how many dimensions the arrays have:


In [107]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Create an array with 5 dimensions and verify that it has 5 dimensions:


In [108]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing
## Get the first element from the following array:


In [109]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


# Get the second element from the following array.


In [110]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


# Get third and fourth elements from the following array and add them.


In [111]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


# Access the 2nd element on 1st dim:



In [112]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


# Access the 5th element on 2nd dim:



In [113]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


# Access the third element of the second array of the first array:


In [114]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# Print the last element from the 2nd dim:


In [115]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing


## Slice elements from index 1 to index 5 from the following array:


In [116]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


# Slice elements from index 4 to the end of the array:


In [117]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


# Slice elements from the beginning to index 4 (not included):


In [118]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# Slice from the index 3 from the end to index 1 from the end:


In [119]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# Return every other element from index 1 to index 5:


In [120]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


# Return every other element from the entire array:



In [121]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


# NumPy Data Types


## Get the data type of an array object:


In [122]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


# Make a copy, change the original array, and display both arrays:


In [123]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# NumPy Array Shape
## Print the shape of a 2-D array:


In [124]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


# NumPy Array Reshaping


# Convert the following 1-D array with 12 elements into a 2-D array.The outermost dimension will have 4 arrays, each with 3 elements:


In [125]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# NumPy Sorting Arrays

## Sort the array:

In [126]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


# 

# 

# 

 # =============================================================================
# EXPERIMENT COMPLETED
# =============================================================================
